# Generated by Django 5.2.4 on 2026-02-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='食材的名称（如：西红柿、鸡胸肉）', max_length=100, unique=True, verbose_name='食材名称')),
                ('category', models.CharField(choices=[('vegetable', '蔬菜'), ('meat', '肉类'), ('seafood', '海鲜'), ('fruit', '水果'), ('grain', '谷物'), ('dairy', '奶制品'), ('egg', '蛋类'), ('seasoning', '调味料'), ('oil', '油类'), ('bean', '豆制品'), ('nuts', '坚果'), ('other', '其他')], default='other', help_text='食材所属的分类', max_length=50, verbose_name='食材分类')),
                ('image_url', models.URLField(blank=True, help_text='食材图片的 URL 地址', max_length=500, null=True, verbose_name='食材图片')),
                ('calories', models.DecimalField(decimal_places=2, default=0, help_text='每 100g 食材的热量（千卡）', max_digits=10, verbose_name='卡路里')),
                ('protein', models.DecimalField(decimal_places=2, default=0, help_text='每 100g 食材的蛋白质含量（克）', max_digits=10, verbose_name='蛋白质')),
                ('fat', models.DecimalField(decimal_places=2, default=0, help_text='每 100g 食材的脂肪含量（克）', max_digits=10, verbose_name='脂肪')),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, help_text='每 100g 食材的碳水化合物含量（克）', max_digits=10, verbose_name='碳水化合物')),
                ('fiber', models.DecimalField(decimal_places=2, default=0, help_text='每 100g 食材的膳食纤维含量（克）', max_digits=10, verbose_name='膳食纤维')),
                ('vitamin', models.JSONField(blank=True, default=dict, help_text='各种维生素的含量（JSON 格式，如：{"C": 19, "A": 900}）', verbose_name='维生素')),
                ('description', models.TextField(blank=True, help_text='食材的详细描述（功效、特点等）', null=True, verbose_name='描述')),
                ('season', models.JSONField(blank=True, default=list, help_text='食材应季的月份列表（如：[5, 6, 7, 8]）', verbose_name='应季月份')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='食材数据创建的时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '食材',
                'verbose_name_plural': '食材',
                'db_table': 'ingredient',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='用户上传的食材图片 URL', max_length=500, verbose_name='图片URL')),
                ('recognition_result', models.JSONField(default=dict, help_text='AI 识别的结果（JSON 格式）', verbose_name='识别结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='识别记录创建的时间', verbose_name='创建时间')),
                ('user', models.ForeignKey(help_text='上传图片的用户', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_recognitions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '食材识别记录',
                'verbose_name_plural': '食材识别记录',
                'db_table': 'ingredient_recognition',
                'ordering': ['-created_at'],
            },
        ),
    ]
