# Generated by Django 5.2.4 on 2026-03-15 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingredient", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="season",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="vitamin",
        ),
    ]
