# Generated by Django 5.2.4 on 2026-02-27 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, help_text='未关联食谱时的自定义食物名称', max_length=100, verbose_name='自定义食物名称')),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='卡路里（千卡）')),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='蛋白质（g）')),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='脂肪（g）')),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='碳水化合物（g）')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '加餐')], default='lunch', max_length=20, verbose_name='餐次')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dietary_logs', to='recipe.recipe', verbose_name='关联食谱')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_logs', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '饮食记录',
                'verbose_name_plural': '饮食记录',
                'db_table': 'dietary_log',
                'ordering': ['date', 'meal_type', 'created_at'],
            },
        ),
    ]
