# Generated by Django 5.2.4 on 2026-03-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dietarylog",
            name="fiber",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="膳食纤维（g）"
            ),
        ),
    ]
