# Generated by Django 5.2.4 on 2026-02-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='用户的显示名称', max_length=50, null=True, verbose_name='昵称')),
                ('avatar', models.URLField(blank=True, help_text='用户头像的 URL 地址', max_length=500, null=True, verbose_name='头像')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], help_text='用户性别', max_length=10, null=True, verbose_name='性别')),
                ('age', models.IntegerField(blank=True, help_text='用户年龄', null=True, verbose_name='年龄')),
                ('phone', models.CharField(blank=True, help_text='用户手机号码', max_length=20, null=True, verbose_name='手机号')),
                ('dietary_preference', models.JSONField(blank=True, default=list, help_text='用户的饮食偏好标签列表（如：素食、低糖、低脂等）', verbose_name='饮食偏好')),
                ('allergies', models.JSONField(blank=True, default=list, help_text='用户对哪些食材过敏', verbose_name='过敏食材')),
                ('health_goal', models.CharField(blank=True, choices=[('lose_weight', '减肥'), ('gain_muscle', '增肌'), ('maintain', '保持健康'), ('improve_nutrition', '改善营养')], help_text='用户的健康目标（如：减肥、增肌、保持健康）', max_length=50, null=True, verbose_name='健康目标')),
                ('daily_calories_target', models.IntegerField(blank=True, help_text='用户每日摄入卡路里的目标值（单位：千卡）', null=True, verbose_name='每日卡路里目标')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='用户档案创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='用户档案最后更新的时间', verbose_name='更新时间')),
                ('user', models.OneToOneField(help_text='关联的 Django 用户', on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'db_table': 'user_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
