# Generated by Django 5.2.4 on 2026-02-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='需要购买的数量', max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='克', help_text='食材的计量单位（克、个、勺等）', max_length=20, verbose_name='单位')),
                ('is_purchased', models.BooleanField(default=False, help_text='是否已经购买该食材', verbose_name='是否已购买')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='添加到购物清单的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最后更新的时间', verbose_name='更新时间')),
                ('ingredient', models.ForeignKey(help_text='需要购买的食材', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to='ingredient.ingredient', verbose_name='食材')),
                ('user', models.ForeignKey(help_text='拥有该购物清单的用户', on_delete=django.db.models.deletion.CASCADE, related_name='shopping_list', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '购物清单',
                'verbose_name_plural': '购物清单',
                'db_table': 'shopping_list',
                'ordering': ['is_purchased', '-created_at'],
                'unique_together': {('user', 'ingredient', 'is_purchased')},
            },
        ),
    ]
