# Generated by Django 5.2.4 on 2026-03-09 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopping", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingListShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="分享 Token",
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("read", "只读"), ("edit", "可编辑")],
                        default="read",
                        max_length=10,
                        verbose_name="权限",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="过期时间")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否有效"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_shares",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="分享者",
                    ),
                ),
            ],
            options={
                "verbose_name": "购物清单分享",
                "verbose_name_plural": "购物清单分享",
                "db_table": "shopping_list_share",
                "ordering": ["-created_at"],
            },
        ),
    ]
