# Generated by Django 5.2.4 on 2026-02-24 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='食谱的标题', max_length=200, verbose_name='食谱名称')),
                ('cover_image', models.URLField(blank=True, help_text='食谱封面图片的 URL', max_length=500, null=True, verbose_name='封面图')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', help_text='食谱的烹饪难度', max_length=20, verbose_name='难度')),
                ('cooking_time', models.IntegerField(default=0, help_text='制作该食谱所需的时间（分钟）', verbose_name='烹饪时间')),
                ('servings', models.IntegerField(default=1, help_text='该食谱可制作的份数', verbose_name='份数')),
                ('category', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('dessert', '甜品'), ('snack', '小吃'), ('soup', '汤品'), ('staple', '主食'), ('other', '其他')], default='other', help_text='食谱所属的分类（早餐、午餐等）', max_length=50, verbose_name='分类')),
                ('cuisine_type', models.CharField(choices=[('chinese', '中餐'), ('cantonese', '粤菜'), ('sichuan', '川菜'), ('hunan', '湘菜'), ('shandong', '鲁菜'), ('jiangsu', '苏菜'), ('zhejiang', '浙菜'), ('fujian', '闽菜'), ('anhui', '徽菜'), ('western', '西餐'), ('japanese', '日料'), ('korean', '韩餐'), ('other', '其他')], default='chinese', help_text='食谱所属的菜系', max_length=50, verbose_name='菜系')),
                ('tags', models.JSONField(blank=True, default=list, help_text='食谱的标签列表（如：快手菜、家常菜）', verbose_name='标签')),
                ('total_calories', models.DecimalField(decimal_places=2, default=0, help_text='整个食谱的总热量（千卡）', max_digits=10, verbose_name='总卡路里')),
                ('description', models.TextField(blank=True, help_text='食谱的详细描述', null=True, verbose_name='简介')),
                ('views', models.IntegerField(default=0, help_text='食谱被浏览的次数', verbose_name='浏览次数')),
                ('likes', models.IntegerField(default=0, help_text='食谱被点赞的次数', verbose_name='点赞数')),
                ('favorites', models.IntegerField(default=0, help_text='食谱被收藏的次数', verbose_name='收藏数')),
                ('is_published', models.BooleanField(default=True, help_text='是否公开显示该食谱', verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='食谱创建的时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='食谱最后更新的时间', verbose_name='更新时间')),
                ('author', models.ForeignKey(help_text='创建该食谱的用户', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '食谱',
                'verbose_name_plural': '食谱',
                'db_table': 'recipe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(help_text='该步骤在食谱中的顺序（从 1 开始）', verbose_name='步骤序号')),
                ('description', models.TextField(help_text='该步骤的详细说明', verbose_name='步骤描述')),
                ('image_url', models.URLField(blank=True, help_text='该步骤的图片 URL', max_length=500, null=True, verbose_name='步骤图片')),
                ('duration', models.IntegerField(default=0, help_text='完成该步骤所需的时间（分钟）', verbose_name='耗时')),
                ('tips', models.TextField(blank=True, help_text='该步骤的注意事项或技巧', null=True, verbose_name='小贴士')),
                ('recipe', models.ForeignKey(help_text='关联的食谱', on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipe.recipe', verbose_name='食谱')),
            ],
            options={
                'verbose_name': '烹饪步骤',
                'verbose_name_plural': '烹饪步骤',
                'db_table': 'cooking_step',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='食材的用量', max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='克', help_text='食材的计量单位（克、个、勺等）', max_length=20, verbose_name='单位')),
                ('is_main', models.BooleanField(default=False, help_text='是否为该食谱的主要食材', verbose_name='是否主料')),
                ('ingredient', models.ForeignKey(help_text='关联的食材', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='ingredient.ingredient', verbose_name='食材')),
                ('recipe', models.ForeignKey(help_text='关联的食谱', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipe.recipe', verbose_name='食谱')),
            ],
            options={
                'verbose_name': '食谱食材',
                'verbose_name_plural': '食谱食材',
                'db_table': 'recipe_ingredient',
                'ordering': ['-is_main', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('view', '浏览'), ('like', '点赞'), ('favorite', '收藏'), ('cook', '完成烹饪')], help_text='用户的行为类型', max_length=20, verbose_name='行为类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='行为发生的时间', verbose_name='创建时间')),
                ('recipe', models.ForeignKey(help_text='行为对象的食谱', on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='recipe.recipe', verbose_name='食谱')),
                ('user', models.ForeignKey(help_text='产生行为的用户', on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户行为',
                'verbose_name_plural': '用户行为',
                'db_table': 'user_behavior',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['author', 'is_published'], name='recipe_author__8fc4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category', 'is_published'], name='recipe_categor_906937_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-views'], name='recipe_views_864ef2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-likes'], name='recipe_likes_1a8244_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cookingstep',
            unique_together={('recipe', 'step_number')},
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['user', 'behavior_type'], name='user_behavi_user_id_f01d25_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['recipe', 'behavior_type'], name='user_behavi_recipe__d7494d_idx'),
        ),
        migrations.AddIndex(
            model_name='userbehavior',
            index=models.Index(fields=['created_at'], name='user_behavi_created_b2be34_idx'),
        ),
    ]
