# Generated by Django 5.2.4 on 2026-03-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.CharField(
                choices=[
                    ("breakfast", "早餐"),
                    ("lunch", "午餐"),
                    ("dinner", "晚餐"),
                    ("dessert", "甜品"),
                    ("snack", "小吃"),
                    ("soup", "饮品"),
                    ("staple", "主食"),
                    ("other", "其他"),
                ],
                default="other",
                help_text="食谱所属的分类（早餐、午餐等）",
                max_length=50,
                verbose_name="分类",
            ),
        ),
    ]
